[package]
name = "primitive_enum"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[lib]

[dependencies]
primitive_enum_macro = { version = "0.1.0", path = "../primitive_enum_macro" }


[dev-dependencies]
# Compatibility test
num_enum = "0.5.1"
