[package]
name = "zhi_enum"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[lib]

[dependencies]
zhi_enum_derive = { version = "0.1.0", path = "../zhi_enum_derive" }


[dev-dependencies]
# Compatibility test
num_enum = "0.5.1"
